version: "2.0"
services:
  db:
    image: "postgres"
    environment:
      CSV_FILENAME: "data.csv"
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
  manager:
    build: .
    depends_on:
      - db
    environment:
      CSV_FILENAME: "data.csv"
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
      